### ISSUE TITLE
SEE stops decompiling prematurely at word EXIT

### ISSUE THREAD

**Issue by bob-g4bby** [flagxor/ueforth#11]
A minor issue with SEE - I just tested the new word RECURSE with this example whilst adding it to the ESP32FORTH glossary:-
: FACTORIAL DUP 2 < IF DROP 1 EXIT THEN DUP 1- RECURSE * ;
When I check the word with SEE, the output is shorter than expected:-
: FACTORIAL  DUP 2 < 0BRANCH DROP 1 ;

**Comment by flagxor** [comment]
Ah, thanks, sorry missed this earlier but fixed recently.
At some point I keep meaning to make SEE smarter to better decode conditionals, but at least now you get the whole definition.
