### ISSUE TITLE
rerun and interval don't work

### ISSUE THREAD

**Issue by MPETREMANN11** [flagxor/ueforth#25]
Hello,
I'm trying this example:

timers
: hi   ." hi" cr   0 rerun ;
' hi 1000000 0 interval ( run hi every second )

It don't work with version 7.0.6.18

It's work with older versions....

BR

**Comment by MPETREMANN11** [comment]
Hello Brad,

I 've found the bug

The problem comme from this line:

swap over 0 swap alarm 2!

in the definition of interval

The word 2! is bugged...

It's easy to control this:

create XXX

   cell 2* allot

My test:

--> 12  34  XXX  2!
 ok
12 -->

The word 2! is also used in timer!

With best regards

**Comment by flagxor** [comment]
Sorry for the regression, this has been fixed in  7.0.6.19
