### ISSUE TITLE
[THEN] at end of xtensa-assembler.fs

### ISSUE THREAD

**Issue by MPETREMANN11** [flagxor/ueforth#29]
Hello,
Why is there a [THEN] at the end of the xtensa-assembler.fs file?
Without [IF]..[ELSE], for me, this [THEN] is not justified.

**Comment by flagxor** [comment]
Oops, yeah had meant to make adding the word conditional.
Fixed in:
https://github.com/flagxor/ueforth/commit/fe87f1574c4d33f6ce66a7199081e5838d7707fe
