### ISSUE TITLE
Word autoexec causes an error STACK UNDERFLOW!

### ISSUE THREAD

**Issue by gerey73** [flagxor/ueforth#37]
`s" /spiffs/autoexec.fs" ['] included catch 2drop drop` - In my opinion , in this line **_2dop_** an extra word!?

**Comment by flagxor** [comment]
Thanks for catching
Fixed in this:
https://github.com/flagxor/ueforth/commit/9ef1ea9f9007b1c807be2c2ee9a289f7fdc34330
