### ISSUE TITLE
Error in path-join

### ISSUE THREAD

**Issue by vkichline** [flagxor/ueforth#52]
Thanks for ueforth! I've been enjoying it immensely!  I ran into an issue and would like to share my findings.
I was unable to include one file from another using full paths. For example, if file1.fs contains: "include /sd/file2.fs", entering "include /sd/file1.fs" will fail.
I found the cause in common/including.fs, in the word path-join.
The third line determines if the file name is a full path, and if so zeros the directory name length. However, the combined string length has already been calculated and is not corrected. This results in the correct string being returned, but with an excessive length, resulting in a file not found error.
I found that simply moving the third line of path-join to the beginning of the word fixes the problem.  There are a few other very minor issues in this word; slightly too much memory is allocated from the heap for paths that begin with ./ and ../ .
I would be happy to prepare a pull request if you like.

**Comment by MPETREMANN11** [comment]
Hi,

**Comment by vkichline** [comment]
Version 7.0.7.12 resolves this issue, better than my suggestion above. Thank you.
