### ISSUE TITLE
ninja: which version? and/or missing D8 

### ISSUE THREAD

**Issue by farvardin** [flagxor/ueforth#61]
I can no longer build ueforth since the switch to ninja.

i get a 

```
./configure.py 
V8 checkout in $HOME/src/v8 not found, ignoring.
Windows %LOCALAPPDATA% not available, Windows support disabled.
Traceback (most recent call last):
  File "/temp/github/forth/ueforth/./configure.py", line 569, in <module>
    Main()
  File "/temp/github/forth/ueforth/./configure.py", line 555, in Main
    InitOutput()
  File "/temp/github/forth/ueforth/./configure.py", line 234, in InitOutput
    D8 = {D8}
NameError: name 'D8' is not defined
```

error

I've tried with python3.6 and python3.8. Which version is required. What is missing? what is this "D8" ?

**Comment by farvardin** [comment]
maybe it's this?

https://www.npmjs.com/package/d8

**Comment by znmeb** [comment]
Nope ... it appears to be a dependency that's installed on `flagxor`'s system but isn't listed in the build instructions in the README. `D8` is an internal variable to the build process. I think it's related to `npm` or `v8`, but I'm neither a Python nor a NodeJS developer, so I can't contribute a patch.

**Comment by farvardin** [comment]
Let's hope @flagxor could help us about this...

**Comment by znmeb** [comment]
Brad has fixed this ... there are still some missing dependencies but I'll open separate issues for those.

**Comment by flagxor** [comment]
Sorry about that.
A bunch of the dependencies logic became more explicit with ninja.
I think I've got this fixed now. Please re-open if not!

**Comment by znmeb** [comment]
Pull request is live.
